// flow-typed signature: 864d844390072e1fda19b2acaff7c831
// flow-typed version: <<STUB>>/react-native-webpack-server_v^0.9.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webpack-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webpack-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-webpack-server/bin/rnws' {
  declare module.exports: any;
}

declare module 'react-native-webpack-server/hot/entry' {
  declare module.exports: any;
}

declare module 'react-native-webpack-server/lib/createBundle' {
  declare module.exports: any;
}

declare module 'react-native-webpack-server/lib/fetch' {
  declare module.exports: any;
}

declare module 'react-native-webpack-server/lib/getReactNativeExternals' {
  declare module.exports: any;
}

declare module 'react-native-webpack-server/lib/Server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-webpack-server/bin/rnws.js' {
  declare module.exports: $Exports<'react-native-webpack-server/bin/rnws'>;
}
declare module 'react-native-webpack-server/hot/entry.js' {
  declare module.exports: $Exports<'react-native-webpack-server/hot/entry'>;
}
declare module 'react-native-webpack-server/lib/createBundle.js' {
  declare module.exports: $Exports<'react-native-webpack-server/lib/createBundle'>;
}
declare module 'react-native-webpack-server/lib/fetch.js' {
  declare module.exports: $Exports<'react-native-webpack-server/lib/fetch'>;
}
declare module 'react-native-webpack-server/lib/getReactNativeExternals.js' {
  declare module.exports: $Exports<'react-native-webpack-server/lib/getReactNativeExternals'>;
}
declare module 'react-native-webpack-server/lib/Server.js' {
  declare module.exports: $Exports<'react-native-webpack-server/lib/Server'>;
}
